### ISSUE TITLE
Release for Scala 3.2.2

### ISSUE THREAD

**Issue by kyri-petrou** [ghik/zerowaste#1]
Scala 3.2.2 was released on Maven Central a few days ago (no github release yet) but I suspect it'll be released officially in the next 1-2 days.

I'm happy to create a PR for it, do I need to add 3.2.2 in `build.sbt` alongside `3.2.1` or replace it? I'm guessing it'd also have to be added to the build matrix in the `.github/workflows/ci.yml` file as well?

**Comment by ghik** [comment]
Hi @kyri-petrou 

Yes, please create a PR if you can. Please add a new version (not replace) and run `sbt githubWorkflowGenerate` to update the github workflows (don't do this manually).

Cheers

**Comment by kyri-petrou** [comment]
Thanks! Just submitted a PR, let me know if I missed something
