### ISSUE TITLE
Support Scala 3.3.0-RC1

### ISSUE THREAD

**Issue by gvolpe** [ghik/zerowaste#3]
Any chances of publishing a milestone or RC for this Scala version? A lot of folks are interested in the new `-Wunused:imports` flag :)

https://github.com/lampepfl/dotty/pull/16157

**Comment by ghik** [comment]
Hi, can you make a PR?
https://github.com/ghik/zerowaste#how-to-submit-a-pr-with-a-new-scala-version

**Comment by gvolpe** [comment]
Happy to do so! Expect one later this evening :)

**Comment by ghik** [comment]
Fixed in 0.2.3

**Comment by kubukoz** [comment]
As a fellow plugin author, I'd like to suggest backpublishing (publishing an artifact under an existing version) - it can be kinda annoying when the plugin keeps getting updates that don't change anything for existing Scala versions, especially if you're trying to support Scala milestones.

I made this: https://github.com/polyvariant/better-tostring/blob/main/project/BackpublishPlugin.scala - for projects publishing with sbt-typelevel, but maybe it can easily be modified to work for your build as well. The downside is that you make these releases locally and not from CI (that should be possible as well, though)

**Comment by ghik** [comment]
@kubukoz yeah, I used to backpublish [silencer](https://github.com/ghik/silencer) but it became sufficiently annoying to publish locally that I dropped it. Maybe I'll look into it again, thanks for the reference.

**Comment by kyri-petrou** [comment]
Out of curiosity, are there any additional checks that this plugin does in Scala versions 3.3.x and above, as opposed to using the new `-Wvalue-discard` compiler flag?

**Comment by gvolpe** [comment]
@kyri-petrou I can only speak as a user of this plugin, and can confirm `-Wvalue-discard` doesn't catch discarded `IO` values, whereas `zerowaste` does: https://gist.github.com/gvolpe/088f6d1a1a8071304b6ae2db444d687c

You can see this program fails to compile, but if you comment out the `using plugin` line, it'll compile without issues. Unrelated, but it looks like a lot of these new flags are still quite buggy --- e.g. the `-Wunused:imports` flag gives some false-positives.

**Comment by kyri-petrou** [comment]
@gvolpe that's quite interesting.. For some reason I can't get the flag to work at all when using scala-cli. In any way, I'll stick with `zerowaste` plugin until the compiler flags are in a more mature state 👍
